#ifndef PUBLIC_HPP
#define PUBLIC_HPP

enum EnMsgType {
    LOGIN_MSG = 1,
    REG_MSG,
    REG_MSG_ACK,
    LOG_MSG_ACK,
    ONE_CHAT_MSG,
    ADD_FRIEND_MSG,
    CREATE_GROUP_MSG,
    ADD_GROUP_MSG,
    GROUP_CHAT_MSG,
    LOGIN_OUT_MSG,
    // Phase 3 feature extensions
    PING_MSG,
    PONG_MSG,
    MSG_ACK,
    USER_SEARCH_MSG,
    USER_SEARCH_ACK,
    FRIEND_REQUEST_MSG,
    FRIEND_ACCEPT_MSG,
    FRIEND_REJECT_MSG,
    FRIEND_NOTIFY_MSG
};

#endif
